// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bxqqqfjomjitvlvyvvvc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJ4cXFxZmpvbWppdHZsdnl2dnZjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc3NTMzNzksImV4cCI6MjA3MzMyOTM3OX0.LlzG2EE1SacuaOZW0xxHPhAVJqWMUjUE1zzIDREUUn4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});